name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e99e39fd222251df112eebfb1f4cd07a7dd5afdc92e2d934433672d2a5cba6"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
