name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e0908981191b3b2e789476a752d8eda5fe38af955e554059a851ab6b0e52d28"

[versions]
forge = "10.13.4.1614"
lwjgl3ify = "3.0.16"
minecraft = "1.7.10"
unsup = "1.2.4"
