name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe0bf2aba942dfc3f9ca3ddb2c7d405b5c275d4b8589b4b063d296f1e3d65f08"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
